### ISSUE TITLE
Error when running the script

### ISSUE THREAD

**Issue by sydios** [poblabs/nagios-nrpe-dynamic-ip-update#1]
Hi,

thanks for the script. But i getting this error when i try to execute the script

sed: -e expression #1, char 87: unterminated `s' command

I use ubuntu

**Comment by poblabs** [comment]
Good question. Do you have `allowed_hosts=` already populated in the nrpe.cfg file? Maybe it's giving the error because it cannot find an IP associated to `allowed_hosts=`.

**Comment by cmos486** [comment]
Config IP 1.1.1.1 is different than xxx.xxx.com IP. Changing config IP to alias
x.x.x.x.x
sed: -e expression #1, char 82: unterminated `s' command
